import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import useSWR from "swr";
import alasql from "alasql";

import type { PagesAndMeta, Page } from "../types";
import { SearchableData } from "./searchable-data";
import styles from "../styles/Home.module.css";

export const Home: NextPage = () => {
  const { data, error } = useSWR<PagesAndMeta, Error>(
    "/api/traits",
    async (url) => {
      const res = await fetch(url);
      if (res.ok) {
        return await res.json();
      }
      throw new Error(`${res.status} on ${url}`);
    }
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {error ? (
          <div>
            Loading error: <code>{error.toString()}</code>
          </div>
        ) : !data ? (
          <div>Loading</div>
        ) : (
          <SearchableData data={data} />
        )}
      </main>
    </div>
  );
};
