name: Build demo to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GH_PAGES_PREFIX: "/docsql"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Cache nextjs build
        uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package*.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Build
        run: npm run build

      - name: Export
        run: npm run export

      - name: Analyze and generate JSON file
        run: |

          set -ex

          tar -zxf example-directories/github-docs-sample.tgz
          npm run analyze -- github-docs-sample/

      - name: Debug what was built
        run: |
          ls -ltr out
          cat out/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: out
