name: Build demo to GitHub Pages

on:
  workflow_dispatch:
  pull_request: # XXX TEMP
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Cache nextjs build
        uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Build
        run: npm run build

      - name: Export
        run: npm run export

      - name: Analyze and generate JSON file
        run: |

          set -ex

          tar -zxvf example-directories/github-docs-sample.tgz
          npm run analyze -- example-directories/github-docs-sample/
          ls -ltr out

      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4.2.3
      #   with:
      #     branch: gh-pages
      #     folder: out
