name: Test development

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  development:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 18
          - 20

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run development
        env:
          PORT: 3000
        run: |
          echo CONTENT_SOURCES=example-directories/my-jamstack-site >> .env
          npm run dev > /tmp/stdout.log 2> /tmp/stderr.log &

      - name: Check that the server started
        run: curl --retry-connrefused --retry 3 -I http://localhost:3000/

      - name: Show server outputs
        run: |
          echo "____STDOUT____"
          cat /tmp/stdout.log
          echo "____STDERR____"
          cat /tmp/stderr.log
