name: Published simulation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          # With v17, as of Nov 2021, you get
          # Error: error:0308010C:digital envelope routines::unsupported
          # node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Cache nextjs build
        uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Build
        run: npm run build

      - name: Export
        run: npm run export

      - name: Package
        run: npm pack

      - name: What was built?
        run: ls -lh

      - name: Extract tarball to temp directory
        run: |
          TARBALL=`ls docsql-*.tgz`
          echo $TARBALL
          TEMP_DIR=`mktemp -d`
          tar -xf $TARBALL --directory $TEMP_DIR
          npx $TEMP_DIR


      # - name: Serve (in the background)
      #   env:
      #     # It's usually the default for `serve` but good to be explicit
      #     PORT: 3000
      #   run: |
      #     npm run serve > /tmp/stdout.log 2> /tmp/stderr.log &

      # - name: Check that the server started
      #   run: curl --retry-connrefused --retry 3 -I http://localhost:3000/

      # - name: View the home page
      #   run: |

      #     curl -v --fail http://localhost:3000/
      #     # XXX Some Playright or jest tests?
      #     curl --fail http://localhost:3000/github/docs-internal
      #     curl --fail http://localhost:3000/github/docs

      # - name: Debug any server outputs
      #   if: failure()
      #   run: |
      #     echo "____STDOUT____"
      #     cat /tmp/stdout.log
      #     echo "____STDERR____"
      #     cat /tmp/stderr.log
