name: Test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm run lint

  test:
    name: Test with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
          - 22

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Cache nextjs build
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package*.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Start server
        env:
          # It's usually the default for `serve` but good to be explicit
          PORT: 3000
        run: |
          echo CONTENT_SOURCES=example-directories/my-jamstack-site >> .env
          npm run run > /tmp/stdout.log 2> /tmp/stderr.log &

      - name: Check that the server started
        run: curl --retry-connrefused --retry 3 -I http://localhost:3000/

      - name: View the home page
        run: |
          curl -v --fail http://localhost:3000/

      - name: Show server outputs
        run: |
          echo "____STDOUT____"
          cat /tmp/stdout.log
          echo "____STDERR____"
          cat /tmp/stderr.log
